customer=input("customer name ")
product=input("product  name")
price=float(input("price"))
quantity=int(input("how much do u want"))
print("========================================")
print("RECEIPT")
print("========================================")
print("customer:",customer)
print ("product price  qty")
print("----------------------------------------")
print("notebook",price,quantity)
print("total",quantity*price)
print("Thank you for shopping!")
print("========================================")
