student-name= input ("enter the student name ")
student_id=input('enter ur id')
department=input('enter ur department')
year=input('enter ur school calendar')
university=input('enter the name ur university')
phone-number=input('enter uur phone number')
print('+--------------------------------+')
print("| Akiba Student Card  |")
print('+--------------------------------+')
print("|student name:{student-name} |")
print("| Id:{student_id} |")
print("|ur department:{department}|")
print("|ur academic calendar:{year} |")
print("|ur university:{university} |")
print("|ur phone-number:{phone-number} |")